# get all books
GET http://localhost:3001/books HTTP/1.1
Content-Type: application/json

###
# create a book
POST http://localhost:3001/books HTTP/1.1
Content-Type: application/json

{
    "title": "Harry Poter"
}

###
# update a book
PUT http://localhost:3001/books/1 HTTP/1.1
Content-Type: application/json

{
    "title": "Dark Tower"
}

###
# delete a book
DELETE http://localhost:3001/books/1 HTTP/1.1
Content-Length: application/josn